# Generated by Django 5.2.6 on 2025-09-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'System Admin'), ('area_manager', 'Area Manager'), ('store_manager', 'Store Manager'), ('area_management', 'Area Management'), ('store_selector', 'Store Selector'), ('visit_creator', 'Visit Creator')], max_length=20),
        ),
    ]
