# Generated by Django 5.2.6 on 2025-10-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0015_area_store_area'),
        ('users', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='areas',
            field=models.ManyToManyField(blank=True, to='checklist.area'),
        ),
    ]
