# Generated by Django 5.2.6 on 2025-09-21 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionplanitem',
            options={'ordering': ['-priority', 'timeframe']},
        ),
        migrations.AddField(
            model_name='actionplanitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actionplanitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='actionplanitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='areamanagervisit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areamanagervisit',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='areamanagervisit',
            name='general_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='areamanagervisit',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='areamanagervisit',
            name='maintenance_needed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='areamanagervisit',
            name='run_out_items',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='areamanagervisit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='requires_follow_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
