# Generated by Django 5.2.6 on 2025-09-22 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_maintenanceticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenanceticket',
            old_name='issue_type',
            new_name='equipment',
        ),
        migrations.RemoveField(
            model_name='maintenanceticket',
            name='visit',
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='maintenance_attachments/'),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('IP', 'In Progress'), ('C', 'Closed')], default='N', max_length=2),
        ),
    ]
