# Generated by Django 5.2.6 on 2025-09-22 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_rename_issue_type_maintenanceticket_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='checklist.areamanagervisit'),
            preserve_default=False,
        ),
    ]
