# Generated by Django 5.2.6 on 2025-09-22 15:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_maintenanceticket_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='areamanagervisit',
            name='time_in',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Time In'),
        ),
        migrations.AddField(
            model_name='areamanagervisit',
            name='time_out',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Out'),
        ),
        migrations.CreateModel(
            name='VisitAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='visit_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='checklist.checklistitem')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='checklist.areamanagervisit')),
            ],
        ),
    ]
