# Generated by Django 5.2.6 on 2025-09-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0009_remove_profile_role_alter_profile_stores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stores',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('admin', 'Area Manager'), ('supervisor', 'Supervisor')], default='user', max_length=20),
        ),
    ]
