# Generated by Django 5.2.6 on 2025-09-22 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0010_remove_profile_stores_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceticket',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='maintenanceticket',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='checklistcategory',
            name='active',
            field=models.BooleanField(default=True, help_text='Mark category as active/inactive'),
        ),
        migrations.AlterField(
            model_name='checklistcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, help_text='Store contact number with country code', max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter valid phone number (e.g. +1234567890)')]),
        ),
    ]
