# Generated by Django 5.2.6 on 2025-09-22 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0011_remove_maintenanceticket_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='equipment_categories',
            field=models.ManyToManyField(blank=True, to='checklist.equipmentcategory'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_number', models.CharField(blank=True, max_length=50)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('maintenance_interval', models.PositiveIntegerField(default=90, help_text='Days between maintenance')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.equipmentcategory')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.store')),
            ],
        ),
    ]
