# Generated by Django 5.2.6 on 2025-09-24 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0012_equipmentcategory_store_equipment_categories_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='areamanagervisit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='areamanagervisit',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='checklist.store'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='checklist.areamanagervisit'),
        ),
    ]
