# Generated by Django 5.2.6 on 2025-10-02 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0016_area_created_at_area_updated_at_area_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenanceticket',
            old_name='description',
            new_name='issue_description',
        ),
    ]
