# Generated by Django 5.2.6 on 2025-09-22 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Change from:
        # ('checklist', '0009_remove_profile_role_alter_profile_stores_and_more'),
        # To:
        ('checklist1111', '0009_remove_profile_role_alter_profile_stores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_access', models.ManyToManyField(blank=True, related_name='user_profiles', to='checklist.store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]