# Generated by Django 5.2.6 on 2025-09-22 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0009_remove_profile_role_alter_profile_stores_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='store_access',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'System Admin'), ('area_manager', 'Area Manager'), ('store_manager', 'Store Manager')], default='user', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='stores',
            field=models.ManyToManyField(blank=True, to='checklist.store'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
