# Generated by Django 5.2.6 on 2025-09-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_store_access_profile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'System Admin'), ('area_manager', 'Area Manager'), ('store_manager', 'Store Manager'), ('area_management', 'Area Management')], max_length=20),
        ),
    ]
